services:
  kafka:
    image: apache/kafka
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:9093'

      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: [ "9092:9092", "29092:29092" ]

  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports: ["5433:5432"]

  publication-db:
    image: postgres:16-alpine
    container_name: publication-db
    environment:
      POSTGRES_USER: pub_admin
      POSTGRES_PASSWORD: pub_secure_password
      POSTGRES_DB: publication_db
    ports: ["5434:5432"]

  local-stack:
    image: localstack/localstack
    container_name: localstack
    ports: ["4566:4566"]
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=ap-south-1
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "./init-scripts:/etc/localstack/init/ready.d"