server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: recommendation-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >-
          user_created_event:com.researchConnect.recommendation.dto.UserCreatedDto,
          publication_created_event:com.researchConnect.recommendation.dto.PublicationCreatedDto

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/recommendation_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
aws:
  s3:
    region: ap-south-1
    access-key: test            # LocalStack accepts dummy credentials
    secret-key: test
    endpoint-override: http://localhost:4566
    bucket-name: research-connect-publications